### ISSUE TITLE
Build fail using quasar-app-extension-ssg

### ISSUE THREAD

**Issue by sptBlack** [yobaji/vue3-google-login#13]
Hey trying to build SSG locally and keep getting this error while building:

```
ReferenceError: document is not defined
    at D:\repos\x-frontend\node_modules\vue3-google-login\dist\index.js:1:598
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\repos\x-frontend\node_modules\vue3-google-login\dist\index.js:1:472)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _require (D:\repos\x-frontend\node_modules\@quasar\ssr-helpers\lib\create-bundle.js:56:9)
```

Are there any solution for this?

**Comment by yobaji** [comment]
@sptBlack Sorry for the late reply and thanks for raising this issue, I have done a small fix for this, can you please use the latest 2.0.12 version and try again and check if the issue still exists?

**Comment by sptBlack** [comment]
Hey it seems working fine now thanks for your quick fix and response!
